### ISSUE TITLE
Cannot post with a 4chan Pass

### ISSUE THREAD

**Issue by alkamine** [K1rakishou/Kuroba-Experimental#1007]
Postng with a 4chan pass logged in errors out with "Authentication required", after which a cloudflare verification dialog loads. completing it does not restore posting functionality.

**Comment by K1rakishou** [comment]
Can you long tap the `send reply button` and then see what setting is enabled in `Reply modes`.

**Comment by alkamine** [comment]
Post with passcode is selected. I have tried changing to other modes and back, logging out and back in, as well as resetting the application and clearing the storage.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/ae07a42c2dafceb8b39cecee185274eeb56b9977

You can wait till this job finishes https://github.com/K1rakishou/Kuroba-Experimental/actions/runs/7766581158/job/21182552775 and then you can try the freshly built beta version with the fix to see if it works. You will find it here: https://github.com/K1rakishou/Kuroba-Experimental-beta/releases

Or you can wait for the regular release.
