### ISSUE TITLE
Can't pass Cloudflare check

### ISSUE THREAD

**Issue by ReSpawN142** [K1rakishou/Kuroba-Experimental#1021]
Always getting this and nothing happens.
![Screenshot_20240218-102816](https://github.com/K1rakishou/Kuroba-Experimental/assets/160385351/b3c98c06-88d0-4e4c-b3a0-8df899f0fed2)

**Comment by K1rakishou** [comment]
The last time this happened to me was because I was trying to use Proxyman to decrypt all the SSL requests/responses that the app made and it didn't work because Proxyman needs to install it's own certificate in order to decrypt the SSL traffic and if Cloudflare detects that certificate it refuses to load it's page. 
So you need to check if you have any custom certificates installed or anything of that sort. Also check the time on your device that it's correct.

**Comment by ReSpawN142** [comment]
Ok problem solved. Needed to change time and reboot phone.
