### ISSUE TITLE
Missing Archive option from menu

### ISSUE THREAD

**Issue by obscenelyvague** [K1rakishou/Kuroba-Experimental#129]
Kuroba has an option to view archives of the respective board you're on from the menu on which it lists the archived threads alongside a search bar, however that option seems to have been removed from this app in favor of supporting archived.moe as 
the designated site for archives?

**Comment by K1rakishou** [comment]
It was removed because there will be other options to view archives. For now you can redirect almost any 4chan thread and open it in Archived.moe. In the next release there will be like 7 more other archives. After that, I'm planning to add support for global search for every archive (+ regular sites that support global search, right now 4chan's search is almost implemented and should make it into the next release).

**Comment by K1rakishou** [comment]
I'm closing this one since the version with all the other archives has been released.
