### ISSUE TITLE
interface reqest: clover-style side pins menu option

### ISSUE THREAD

**Issue by 1sad** [K1rakishou/Kuroba-Experimental#169]
please, could you add an option for clover-style side pins panel?

I know different people might browse differently, but for me having history on the slide menu is uncomfortable cause I rarely use history and I pin a lot of threads. one downside of history is that it always shuffles around as you browse.

another issue is having the bottom panel take a lot of vertical space, I realise it goes away when you scroll but its still kind of uncomfortable. if it was on the sliding panel it feels more ergonomic and saves space.

sorry if this is annoying, it would be nice to just be able to swap the history to a button and pins to the left slide panel, maybe some way to hide the bottom panel.

**Comment by K1rakishou** [comment]
One of the points of this fork was switching to tabs-based navigation and to do that all the stuff from the drawer had to be moved somewhere. That's how BottomNavigationView was introduced. Adding a setting for old-style drawer is not an option because it's going to be a pain in the ass to support both of them. I can add an option so that the tabs do not move around when you open boards/thread. I have already increased the max amount of them (not in this version yet). But no, there are no plans to make it behave like in Clover/Kuroba because there are already Clover/Kuroba with that behavior.

**Comment by K1rakishou** [comment]
Oh yeah, I'm also planning to upgrade tabs to behave like foreground-only bookmarks (basically like bookmarks but they will only be updated while the app is in foreground) so this is probably something similar to what you want.

**Comment by 1sad** [comment]
I see. thanks.

**Comment by 1sad** [comment]
how about allowing to manually sort history entries and allowing a setting to ONLY show pinned threads in the history?
would that be easy to implement?

**Comment by K1rakishou** [comment]
Shouldn't be hard.

**Comment by 1sad** [comment]
Thank you
would also be nice to pin straight to history as a setting
instead of pinning, then going to pins, opening each thread for them to appear in history, 
its a quality of life idea at this point, and people browse differently, so maybe its just my habits
id be happy with any of these changes, thanks again!

**Comment by K1rakishou** [comment]
Gonna close this issue since it's very old, some stuff was implemented and some won't be implemented.
