### ISSUE TITLE
Replies containing images don't work

### ISSUE THREAD

**Issue by eclipseo** [K1rakishou/Kuroba-Experimental#249]
4chan with nojs on v 0.3.1.4138

When I reply to a thread with a picture, the post is displayed as processed, but never appear on the thread as if it was never posted. Text only reply works normally.

Any way I can help to debug that?

**Comment by K1rakishou** [comment]
That's strange. What board this happens on?

**Comment by eclipseo** [comment]
@K1rakishou /b/ /bant/ don't, /k/ works, /s/ works /g/ works. So mostly b

**Comment by eclipseo** [comment]
Well it works when I cut my ad blocker, which is strange because I don't have this issue with kuroba proper.

**Comment by K1rakishou** [comment]
Damn, this shit is weird as fuck. The server returns a successful response, it returns a thread/post number as a reply but there is no post in that thread with such post number! What the fuck? This seems like a 4chan bug. And I have a hunch it is a "4chan.org" bug not "4channel.org" because this doesn't happen on "4channel.org" boards. And you can't find that post using global search too! And yeah it only happens when you attach a file.

**Comment by K1rakishou** [comment]
Alright, I figured it out. It's because of user-agent. For some reason it won't show your post when trying to post with this user agent - "Mozilla/5.0 (Linux; Android 8.1.0; Android SDK built for x86) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.127 Mobile Safari/537.36"

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/f325df203bf5b71bc2000d47e51e2e460b157c7c

**Comment by eclipseo** [comment]
Hey thanks for fixing this!
