### ISSUE TITLE
[Feature] Importing From Kuroba

### ISSUE THREAD

**Issue by seniorm0ment** [K1rakishou/Kuroba-Experimental#278]
Requesting the ability to import config from Kuroba for easy migration.

**Comment by K1rakishou** [comment]
It is already possible but the settings file must be exported from Kuroba version 4.13.X-release (not dev!). If it doesn't work for some reason then I will need your settings file to debug the issue.

**Comment by seniorm0ment** [comment]
Yeah it just crashes the app for me after selecting the file to import.
Not really comfortable giving the export, as it has my history and watched threads. 
Are you not having issues?

Migrating from Kuroba 4.13.6  

Edit: I just manually migrated and deleted Kuroba.

**Comment by K1rakishou** [comment]
It's probably not a crash; it's supposed to restart the app after importing the stuff. The problem is most likely in the database schema changes (especially the Site class) so it cannot find stuff to import and thus not doing anything. It works fine for me when using the settings file exported from 4.13.6-release.
