### ISSUE TITLE
BookmarkWatcherWorker's execution sometimes canceled right after being started

### ISSUE THREAD

**Issue by ChillHorse** [K1rakishou/Kuroba-Experimental#296]
Due to various android vendors app management kurobas thread watcher won't always work in background even if it's whitelisted. I was wondering if a widget could solve this in a way. 
Would it make sense to implement this someday?

**Comment by K1rakishou** [comment]
>Due to various android vendors app management kurobas thread watcher won't always work in background even if it's whitelisted. I was wondering if a widget could solve this in a way.

No it shouldn't matter since this application uses [Services](https://developer.android.com/guide/components/services) which are "supposed" to run when the main app is dead. If it still doesn't work then it's either an application bug (and in this case I need logs), either the phone itself blocks the service for some reason (like most of the chinese phones do) and I can't do anything here. There were also bugs in the Google's WorkManager library that could prevent the tasks running while the app is dead (which I use to handle tasks that run when the app is dead. I have already updated it but it's not released yet).

>Would it make sense to implement this someday?

I have never worked with widgets but I'd heard that it's a real pain in the ass to make one.

Also, you have probably already seen this link, since I show it when you enable background watcher, but just in case - https://dontkillmyapp.com/

**Comment by ChillHorse** [comment]
My current phone is a Sony Xperia 5 (Android 11) for which Kuroba is pretty dead when in background.
I already knew about dontkillmyapp but it doesn't solve the issue with stopped/paused service. 
I'll keep an eye on the logs this week and upload them if I find anything.

**Comment by K1rakishou** [comment]
>My current phone is a Sony Xperia 5 (Android 11) for which Kuroba is pretty dead when in background.

Do this happen with other applications or only KurobaEx?

**Comment by ChillHorse** [comment]
> Do this happen with other applications or only KurobaEx?

At least it's the only one where it's noticeable. 
The applications which receives the most notifications on my phone are element (matrix client), telegram, vivaldi browser and nine (email client) and these get notification even quicker than their desktop variants.
Element seems be a special case since Stamina mode automatically restricted the app but it's still getting notifications as quickly as the desktop/web client without being opened at all

**Comment by K1rakishou** [comment]
Wait, you have Stamina mode activated?

**Comment by ChillHorse** [comment]
Not reallly, no it is set to activate once the battery is down to 15%. Otherwise it is not active.

**Comment by K1rakishou** [comment]
Oh I see. Well then I would like to see the logs just to be sure it's not the app's bug. Basically, you just need to bookmark a thread, mark any post as your own, kill the app, maybe wait 15-30 minutes until the phone is asleep then reply to that post and wait. It would really help to see the logs for the whole period starting with the thread bookmarking.
Here is a guide on how to collect the logs - https://github.com/K1rakishou/Kuroba-Experimental/wiki/Getting-application-logs-or-crashlogs-on-beta-or-release-builds because the app's internal logger probably won't be enough since there is a limit on how many lines can be shown.

**Comment by ChillHorse** [comment]
besides the guide missing a quote in the last line it did not work for me. I either get permission denied or file not found. No idea why it would also ignore backslash on Windows. The file does exists
![Screenshot 2021-02-18 151656](https://user-images.githubusercontent.com/17539404/108373257-fbcc4700-71ff-11eb-99d2-58d411d9b29d.jpeg)
---

I now set the watcher interval to 5min and waited 6min before opening the app to get the log. The first one is in the middle of a thread
[KuroExLogWith5minWatcher.txt](https://github.com/K1rakishou/Kuroba-Experimental/files/6003549/KuroExLogWith5minWatcher.txt)
---
this log should contain the creation of a new thread on /b/ with a reply shortly after but it did not trigger a notification. Watcher interval remained 5min here also
[KuroExLogWith5minWatcher2.txt](https://github.com/K1rakishou/Kuroba-Experimental/files/6003573/KuroExLogWith5minWatcher2.txt)

**Comment by K1rakishou** [comment]
Alright, judging by the logs the service indeed was never called while the app was in background. 

```
D/KurobaEx-beta | BookmarkWatcherDelegate: BookmarkWatcherDelegate.doWork() called, isCalledFromForeground=true, currentThreadDescriptor=TD{4chan/b/847689100}
```

You can tell that by searching for all occurrences of `isCalledFromForeground=false` (There are 0 of them, you can only find `isCalledFromForeground=true`  meaning it was called when the app was in foreground). This means that either
1. Indeed the phone killed the background service.
2. The OS just decided to postpone the update until later (since you only waited for 6 minutes and the interval is set to 5 minutes, sometimes the OS may decide to invoke background tasks a little bit later, so this thing may be imprecise) and you opened the app before the service was called.

One strange thing that I noticed, apparently the notification wasn't shown even when you opened the application which should have been shown, so I need to clarify this - was the notification shown after the app start or was it never shown? Also, do notifications show up when the app is in foreground? (By the way, if you are reading a thread and you get a reply in that thread the notification won't be shown, this is intentional).

**Comment by ChillHorse** [comment]
>the OS may decide to invoke background tasks a little bit later, so this thing may be imprecise) and you opened the app before the service was called.
I was creating this issue because it never worked in background for me. Only when oping the app again.

While testing on the first log I did forgot about the in app notification not being displayed in the app. 

With the second I was impatient and pulled to refresh on the bookmark tab. There it also won't be displayed as far as I remember. But being inside different threads and getting reply notifications does work for me.

Just doesn't works since a few updates when in background or closed. For my testing kuroba was in background

**Comment by K1rakishou** [comment]
Alright, I found a bug that sometimes prevents the background service to be executed but for me it only happens once in a while not always like in your case.

**Comment by ChillHorse** [comment]
>but for me it only happens once in a while not always like in your case


I think this is partially related to Sony, my previous phone was a Blackberry KeyOne with Android 7, it did work reliable on this one

**Comment by ChillHorse** [comment]
> but for me it only happens once in a while not always like in your case

I think this is partially related to Sony, my previous phone was a Blackberry KeyOne with Android 7, it did work reliable on this one

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/950c1e0dcf32052e419522b327a7f32dc2b3f095
