### ISSUE TITLE
Lainchan "15 freshly bumped threads" boards are broken

### ISSUE THREAD

**Issue by Rult** [K1rakishou/Kuroba-Experimental#320]
/psy/ and /culture/ boards show this error:
`FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY[787])`

App version: 0.6.5 F-Droid
OS version: Android 11

**Comment by K1rakishou** [comment]
>Lainchan "15 freshly bumped threads" boards are broken

Yeah this is because of https://github.com/lainchan/lainchan/issues/187

**Comment by K1rakishou** [comment]
>/psy/ and /culture/ boards show this error:
>FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY[787])

This has the same reason as https://github.com/K1rakishou/Kuroba-Experimental/issues/320#issuecomment-803607619

It is possible to fix this on my side (by additionally parsing the page HTML) but I think this should be implemented on their side.

You could help by going there https://github.com/lainchan/lainchan/issues/187 and bumping the issue.

**Comment by K1rakishou** [comment]
To clarify why this error is happening: currently there are two threads on /psy/ with the same id "1", but they belong to different boards (/zzz/ and /drugs/). But since there is no information about which board those threads belong to in the catalog API I assume they belong to /psy/ boards which is incorrect.
