### ISSUE TITLE
[BUG] thread page numbers reported incorrectly

### ISSUE THREAD

**Issue by tidux** [K1rakishou/Kuroba-Experimental#351]
Thread page numbers for 4chan threads sometimes fail to update for hours at a time, even when loading new posts, even after a full close/restart of the app.  Please ensure it is fetched and updated consistently, ESPECIALLY for threads past bump limit.  Clover and Kuroba never had this problem so I suspect it's a regression.

**Comment by tidux** [comment]
Also possibly related: deleted posts/images aren't removed from the count at the bottom of the thread.  This is starting to smell like an overly aggressive caching problem. Please try switching to full thread fetching on every update.  Using more bandwidth is preferable to incorrect data display.

**Comment by K1rakishou** [comment]
>Thread page numbers for 4chan threads

You mean the page counter at the bottom of a thread or the counter in bookmarks?

>Also possibly related: deleted posts/images aren't removed from the count at the bottom of the thread. This is starting to smell like an overly aggressive caching problem.

Yeah this is because all posts are cached in the database/memory and I don't filter deleted posts out when loading new posts normally. There will be new options in the next version where you will be able to clear deleted posts in a thread.

>Please try switching to full thread fetching on every update

It always loads threads fully from the server because almost all sites do not support partial updates.

**Comment by tidux** [comment]
Page counter at the bottom of the thread.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/5e811df96a06f5448598577296bf3d4cea44f1eb
