### ISSUE TITLE
Report "Side drawer buttons clip status bar making them untappable"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#356]
UUID: 3082ee8df5911fc45dc0778122d1f7f3
Build flavor: stable
Version name: v0.7.6
OS info: Android 11, sdk version: 30
Report description: Side drawer buttons clip the status bar, making the buttons untappable:
https://i.imgur.com/WAXhM83.jpg

**Comment by K1rakishou** [comment]
You should be able to scroll it.

**Comment by barabraa** [comment]
Yeah, I noticed that now, but I don't think you should be able to scroll the side drawer so that the buttons go below the status bar. I assume if you have enough threads in history or bookmarks you can make the buttons disappear completely by just scrolling down far enough. The buttons should be in static position, not part of the scrollable element IMO.

**Comment by K1rakishou** [comment]
I made it scrollable so you have more space because I though I might add more menus there in the future. And I mean it's not like those menus are supposed to be used that often. Well maybe the theme switch button, but I dunno why would anyone use it so often that it becomes uncomfortable.
