### ISSUE TITLE
Sometimes app crashes when trying to attach a file

### ISSUE THREAD

**Issue by cuteasci** [K1rakishou/Kuroba-Experimental#382]
You press plus button, it opens recent file dialog and after half a second it crashes. 

Android 11
Miui 12.6

Log:
https://pastebin.com/fcANbDV1

**Comment by K1rakishou** [comment]
Do you, by any chance, have any kind of developer settings enabled, like "Don't keep activities"?

**Comment by K1rakishou** [comment]
So judging by the logs, when the file picker activity is started Kuroba's main activity is destroyed for some unknown reason. Because of this everything is getting canceled and de-initialized then pickFile task is canceled which calls other UI cancelation tasks and since the UI already de-initialized it crashes.

```
D/(16:37:07.398) KurobaEx-beta | StartActivity: stop
D/(16:37:07.410) KurobaEx-beta | StartActivity: onDestroy()
```

The second line shouldn't be printed normally. It is printed for me with "Don't keep activities" developer setting turned on, though. But it doesn't crash for some reason. Anyway this shouldn't be happening.

**Comment by cuteasci** [comment]
> Do you, by any chance, have any kind of developer settings enabled, like "Don't keep activities"?

It turned off. 

Here is more logs 
https://pastebin.com/qePcV63b

**Comment by K1rakishou** [comment]
This crash seems like it's happening somewhere inside the default "Files" application.

**Comment by cuteasci** [comment]
The problem has gone after updating the ROM
