### ISSUE TITLE
Play protect detects the app to be perhaps malicious.

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#399]
![Screenshot_20210516-030102_Google Play Store](https://user-images.githubusercontent.com/16048625/118383152-57d21c00-b5f3-11eb-8fd9-e87e2b82340f.jpg)

**Comment by ghost** [comment]
This happened during the update (from 0.8.2 to 0.8.7)

**Comment by K1rakishou** [comment]
The fucking "play protect" malware dares to call another app harmful, holy shit. (I bet it's triggered by 2captcha.com domain because it's used to solve their captcha).
Solution: click "Install anyway" or delete play store.

You can also see for yourself what code has been changed between 0.8.2..0.8.9 release if you don't trust me or something.

https://github.com/K1rakishou/Kuroba-Experimental/compare/v0.8.2-release...v0.8.9-release
