### ISSUE TITLE
captcha doesn't count when post is qued up

### ISSUE THREAD

**Issue by 1sad** [K1rakishou/Kuroba-Experimental#400]
basically when on cooldown, no matter how short, captcha will not count for the post when you press send
have to resolve again after it errors after timer ticks down
or manually que up another captcha before timer runs out (but it still makes you solve one when you click send, so its double the work)

**Comment by K1rakishou** [comment]
When you send a reply and the server detects any kind of error (file too big, no comment or you are posting too fast) the captcha you sent is getting marked as already used so you will have to solve it again. That's how 4chan works. Automatic captcha solvers should make it easier for you since the captcha will be solved automatically.

**Comment by 1sad** [comment]
but it works with manually stored captcha?

**Comment by K1rakishou** [comment]
Wait I don't get it. Can you describe the step you do and what result you are expecting?

**Comment by 1sad** [comment]
I post
captcha popup
enter captcha
cooldown ends
"authorization failed"
have to enter captcha again

if while its on coopdown I store another captcha manually, it works
is that what you're talking about? 1 captcha gets eaten?

I don't think it happens on PC with 4chan x but also on PC you don't even have to enter captcha every time for somecreason

**Comment by K1rakishou** [comment]
So what happens is:
1. You click "send post" button.
2. You enter captcha.
3. Post is sent to the server. The captcha that you just solved is removed from the app memory since it can't be used again anymore.
4. Server detects that you post too fast (or whatever other error).
5. Captcha is marked as used and server sends response back to the app.
6. The app receives the server response that tells it that you have to wait N minutes until you can post.
7. The times passes.
8. Since you are most likely using "Solve captcha then post" reply mode it asks you to solve captcha right away before sending the reply again. 

So you can change the reply mode to "Attempt to post without solving captcha" but the server (at least it's like this on 4chan) will 100% tell you that you need to solve the captcha. You can also start using captcha solvers so the 8th step will automatically go to the 3rd step without your interaction whatsoever.

>if while its on coopdown I store another captcha manually, it works
is that what you're talking about? 1 captcha gets eaten?

Yes, that old captcha is removed after any response is received from the server. Then once the wait time is over it checks whether there is a solved captcha in the captcha storage and if there is it takes it and automatically sends the post back to the server with that captcha.

**Comment by 1sad** [comment]
i see...
is there any way to integrate cookies from the desktop browser s you dont have to solve captcha for every post? or do you have to run JS captcha for that?

**Comment by K1rakishou** [comment]
> or do you have to run JS captcha for that?

This. And I don't think it will allow you to skip captchas. They will be solved automatically sometimes, meaning, you will get the green checkmark. But sometimes it will literally spam you with different kind of captcha + slowly fading captcha and other shit. And the more you post the more captcha it will force you to solve. JS recaptcha is awful.

**Comment by 1sad** [comment]
i see, thank you
