### ISSUE TITLE
Fast scrolling as if I am scrolling on edge of screen

### ISSUE THREAD

**Issue by reportthings** [K1rakishou/Kuroba-Experimental#424]
When opening a thread, swiping up to progress through the thread enables the fast-scroll 90% of the time.   Only occurs if I try scrolling before the thread has been open for ~3 seconds.

Example:
Open thread, slowly slide my finger up, starting from the middle of the screen, scrolls me instantly to the middle of the thread as if I am scrolling on the very edge of the screen and continues to fast scroll whichever direction I move my finger until released.

**Comment by K1rakishou** [comment]
Maybe you are accidentally touching the scrollbar? There is a setting to disable that behavior. It's called "draggable scrollbars". You can change the type so it won't scroll when you tap any area of the scrollbar and only scroll when you drag the thumb.

**Comment by reportthings** [comment]
Thanks for the reply.  I did manage to fix it with the draggable scrollbars.  Though I am 100% sure that with the "scroll by clicking any point of track" option enabled, it assumes I am clicking the track but I am not.  I have recorded a video showcasing this, with touches and touch data enabled.

http://imgur.com/a/qmrSaBI

Whether it's my phone or the app, the draggable scrollbars is perfectly fine for me to use.  Also thanks for making the app, I love it.

If you need any other information I can provide it

Thanks

**Comment by K1rakishou** [comment]
Oh it may be because you are using Android gestures and doing the back gesture right on top of the scrollbar so the scrollbar starts scrolling and at the same time you are going back to the catalog and it's getting stuck in the "scrolling" state so when you are going back to the thread it's still in the scrolling state. Something like this. Yeah, "tap any area of scrollbar to start scrolling" doesn't really work with Android gestures that's why there is the other option to only scroll when dragging the scrollbar thumb.

**Comment by K1rakishou** [comment]
I guess this can be fixed.

**Comment by reportthings** [comment]
Yes you are right! It is android gestures.  Thanks again for your help I'll close this now.  Take care.
