### ISSUE TITLE
Optional post formatting options like in Kuroba

### ISSUE THREAD

**Issue by crisalis2** [K1rakishou/Kuroba-Experimental#499]
Kuroba has non-standard quotes support (making things such as @12346789 work like >>123456789), >emoji support (I think you deliberately removed this when you forked Kuroba, so maybe you won't consider it) and markdown support. I think it would be nice to have those in KurobaEx too. Specially the non-tandard quotes thing that many posters who try not to give (you)s use.

**Comment by K1rakishou** [comment]
I don't remember whether it was even present in Kuroba 4.12.0, on which this fork is based on, or I had removed it myself. Anyway, it's not supported by 4chan so that's why I don't want to add support to this.
Emojis were removed when I forked Kuroba, yes, and I'm 100% not planning on bringing them back.
