### ISSUE TITLE
Touching an URL

### ISSUE THREAD

**Issue by 213a21g** [K1rakishou/Kuroba-Experimental#504]
If I touch anywhere in those rectangles, it'll click on the URL inside the rectangle, even when the touch wasn't on the URL itself. Does anyone else have the same issue too? 

![5](https://user-images.githubusercontent.com/87037553/127057774-1c2904a6-a167-4b4b-ad25-ab2c19b5ca74.jpg)

**Comment by K1rakishou** [comment]
That's how it always worked since Clover.

**Comment by 213a21g** [comment]
But this isn't Clover. I'll then request to have it changed so that an URL can only be clicked when someone touches the URL itself.

**Comment by seniorm0ment** [comment]
This is something that is really annoying, and I also don't remember it on older versions of KurobaEx. It was one of the recent updates that caused this change. It makes it almost impossible to use one handed, and also on posts with only links it's basically impossible to hold down to show the context menu.
I expect to press anywhere on white space to show context menu, and only click links when I click links. That's pretty standard across all apps.

**Comment by K1rakishou** [comment]
>and I also don't remember it on older versions of KurobaEx.

It literally was like this since the Clover days (Maybe it was broken temporary?). And yes it was done intentionally. I guess to make it easier to click post quotes because otherwise you would have to reach your finger all the way to the left side.

![image](https://user-images.githubusercontent.com/10332458/135258357-33ff6e02-e91a-4465-be20-c40ccd2fa4f6.png)

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/44f269588b9547f8fc7330d1b759d64034c2c4db
