### ISSUE TITLE
[Feature] Move/Add Post Error Notifications In App

### ISSUE THREAD

**Issue by seniorm0ment** [K1rakishou/Kuroba-Experimental#524]
Requesting re-adding posting notifications within the app (such as errors when posting, and the upload %). It's a little annoying that it only shows in the notifications dropdown on Android.

**Comment by K1rakishou** [comment]
What's wrong with the notification? It's one of the official ways to implement this kind of stuff.
https://developer.android.com/training/notify-user/build-notification#progressbar

Moreover, the post data uploading is executed in a background service meaning once it's started it will continue uploading even if you close the application (but don't force stop it because it's a completely different thing). And in order to communicate with the user from a background service you are kinda supposed to use the notifications.
https://developer.android.com/guide/components/services#Notifications

**Comment by seniorm0ment** [comment]
nothing is wrong with the post notification, however it is annoying to need to pull down the notification to see why a post is pending (ratelimit, error, etc). It's good for when the app is not focused, but while it's focused this information should *also* be displayed right in the app above the post dialog.

**Comment by K1rakishou** [comment]
It should display that info in the reply layout as well. If it doesn't then it's a bug.

**Comment by K1rakishou** [comment]
I guess I could make it so that it always shows the error in the reply layout when you open it until you swipe away the error notification.

**Comment by K1rakishou** [comment]
Alright now the error will be displayed in the reply layout every time you open it until:
1. You swipe away the notification manually.
2. You click the reply layout floating error.

Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/f826332536a68fdadc8d2fce57cc907514abf9e3
