### ISSUE TITLE
The image loading error is still present.

### ISSUE THREAD

**Issue by AntonioVOL** [K1rakishou/Kuroba-Experimental#539]
The image loading bug is still present although it has been fixed in kurobaex-beta in the latest version.

To demonstrate this I use the beta app of 'kurobaex'.

http://imgur.com/gallery/nZUvKWq

This error only happens when I have the mobile in vertical and I load an image that is horizontal as you can see in the video, I think that the other way round (when I load a wallpaper image for mobile and display it horizontally for example) also happens, please fix it.

I tested the load with horiizontal images with screen horizontal and in some large resolution images the error happens

**Comment by K1rakishou** [comment]
If there is no crash log and no way to reproduce it then I can't do anything. It might as well be a native crash somewhere deep inside the Android OS itself that's why there is no crash log. You can try other clients (Clover/Kuroba, they use the same image viewing library) and see whether the same thing happens or not. If it still happens then it's definitely not the app's problem.
