### ISSUE TITLE
[Feature rekwest] Add option to force showpost details on the right/left

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#580]
![Screenshot_20211007-212033_KurobaEx-fdroid](https://user-images.githubusercontent.com/88936537/136419802-3e3960a7-d5eb-435d-b996-e23dfe0da00d.png)
Like this, but always and not only when possible
I have found that the UI looks a lot more coherent that way.
Addtionally, an option to align the replies and images detail would also be nice

Btw, whats the difference btw phone and slide mode? Couldnt notice any

Lastly, thanks a ton for the amazing, free app, its the best!

**Comment by K1rakishou** [comment]
>Addtionally, an option to align the replies and images detail would also be nice

One request per issue, please.

>Btw, whats the difference btw phone and slide mode? Couldnt notice any

Not much difference anymore, pretty much slide mode just adds the right panel overhang. In Clover/Kuroba (early versions) it was used for controller navigation stacking (when you open a thread from within another thread) but it's not used anymore since there is a different way to do that now in KurobaEx.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/8ffb62bd8dd97e2929d94f7bab5ac17e86b5f6c6

**Comment by ghost** [comment]
Wow, nice!
