### ISSUE TITLE
UI bug report

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#582]
See attached screen recording

https://user-images.githubusercontent.com/88936537/136588535-5421dd4e-908b-4bfe-93ff-ec07ea57a67b.mp4

Version - latest fdroid 0.12.8

**Comment by ghost** [comment]
The replies popup view should not be shown when I am typing a new reply

**Comment by K1rakishou** [comment]
This was done intentionally so that you can quote in reply chains. Otherwise I could always close the reply chain once you quote someone but I bet that's not what most people would want to happen. Just quote whoever you want and then close the reply chain. And no it's not possible to just show the reply layout on top of the all reply popup because they are in separate planes of existence.

**Comment by ghost** [comment]
Oh, sorry, thought this was a bug
