### ISSUE TITLE
Cache is stored in data directory

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#585]
Termux log to show that data is stored in files/filecache instead of cache/
```
Welcome to Termux!

Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on libera.chat

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

~ $ su
:/data/data/com.termux/files/home # cd /data/data/com.github.k1
com.github.k1rakishou.chan.beta/       com.github.k1rakishou.chan.fdroid/
:/data/data/com.termux/files/home # cd /data/data/com.github.k1rakishou.chan.fdroid
:/data/data/com.github.k1rakishou.chan.fdroid # du -sh *
4.0K    app_textures
232K    app_webview
4.0K    cache
4.0K    code_cache
8.6M    databases
103M    files
584K    no_backup
20K     shared_prefs
:/data/data/com.github.k1rakishou.chan.fdroid # cd files
:/data/data/com.github.k1rakishou.chan.fdroid/files # du -sh filecache
103M    filecache
:/data/data/com.github.k1rakishou.chan.fdroid/files #

```
Roughly 103 MB, mostly images. I know that there is a way to clear cache in the app, but wouldnt it be better to store in just cache/ instead?

**Comment by ghost** [comment]
>https://github.com/K1rakishou/Kuroba-Experimental/blob/b71fd47aef0d8f7ddebda0050c012bf36013bea9/Kuroba/app/src/main/java/com/github/k1rakishou/chan/core/manager/ApplicationMigrationManager.kt#L61

This appears to be intentional according to the commit message. Since the problem appears to be images not loading, can cachehandler not just request the images from the server again? 103 MB after only a few days is a lot I think.

**Comment by K1rakishou** [comment]
The problem is that Android OS itself may randomly decide to start clearing cache directories of the installed apps even when they are running and this breaks the app. It breaks because I keep a HashSet of the files that are currently cached on the disk in the memory so that I can quickly check whether it's already cached and when the Android decides to clean it there is no way for me to know that it happened and it ends up in a situation where the app thinks that a file is already cached (because it says so in the memory cache) but it actually isn't because it doesn't exist on the disk anymore. To fix that I would have to always double check whether the file exists on the disk but that would kill the performance in some places and the whole point of the memory cache. So it was decided to move that stuff into the data directory.

**Comment by K1rakishou** [comment]
You can decrease the disk cache max size in the settings. 128MB is the minimum allowed cache size. It may seem a lot but in reality it isn't because some image boards allow attaching webms that may weight up to 25MB or even more.

**Comment by ghost** [comment]
Alright

**Comment by ghost** [comment]
Btw, really appreciate your detailed responses and active commitment to a foss app, not many devs are like that
