### ISSUE TITLE
Add ability to match posts with empty comment

### ISSUE THREAD

**Issue by lplp6lkhp** [K1rakishou/Kuroba-Experimental#599]
I have this filter on both Kuroba and KurobaEx (and 4chanX). It only doesn't work on Ex:
`/^$/`
Ideally this is supposed to hide any posts containing an empty string - so it would match posts containing an image, but no text. Useful for the waifu spam on /vg/. This doesn't work on Ex. 

I also have some filters that work differently across Ex/Kuroba/regex101 but I'm not sure if it'd be trickier to fix.

I have this filter in 4chanX:
`/(>{1,2}\d+\n\+\s?\d|^\+\s?\d)/gmi`

Meant to match +1 (more waifushit) posts without matching something like "this move is +1 on block". But this doesnt work on Kuroba either, only 4chanX/regex101, so it might be harder to fix. Still, it behaves differently in Ex and Kuroba so maybe there's a bug here.

This works as intended on 4chanX/regex101, matches nothing in Kuroba, and matches anything that isn't an empty string in Ex.

**Comment by K1rakishou** [comment]
>/^$/

Yeah this one doesn't work because there is an optimization to not apply regex for posts with empty comments.
`&& post.postCommentBuilder.getComment().length() > 0`

To fix that I guess I could add a new checkbox something like "apply to posts with no comment".

>/(>{1,2}\d+\n\+\s?\d|^\+\s?\d)/

This one is kinda complex so it's hard to tell why it doesn't work. At the very least in `/gmi` the `gm` flags are not supported. 
I found a pattern that detects multiple quotes in a post so maybe you can modify that to make your own filter.

`/(>>\d+( \(\w+\))?[ |\n]){2}/`

![image](https://user-images.githubusercontent.com/10332458/137584225-3fac962f-698d-4dfb-b3d4-7be3d9282ef3.png)

**Comment by K1rakishou** [comment]
Oh I guess just removing the `gm` is enough to make it work.

![image](https://user-images.githubusercontent.com/10332458/137584403-6ed46900-fda9-445c-a97f-4124cbbe6501.png)

**Comment by K1rakishou** [comment]
I will add support for the m flag, but unfortunately there is no alternative for the g flag.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/4697fcb90c36b8dec6bc2107b5ccfebe5393ae1e

**Comment by lplp6lkhp** [comment]
Thank you so much. 

> Oh I guess just removing the `gm` is enough to make it work.
> 
> ![image](https://user-images.githubusercontent.com/10332458/137584403-6ed46900-fda9-445c-a97f-4124cbbe6501.png)

The issue isn't that it isn't matching, it's that it's matching _everything_ 
![Screenshot_20211016-110447](https://user-images.githubusercontent.com/42627495/137592423-494fdf69-f3fd-4b84-9097-9297e1593a7a.jpg)

It is a bit complex so maybe not possible, which is fine!
