### ISSUE TITLE
detect if flags are enabled in a board instead relying on a hardcoded whitelist

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#768]
/lgbt/ has enabled flags, whether this is permanent or not we don't know, but it's impossible to set flags for /lgbt/ because normally it doesn't has flags.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/543558f80a45e1a13745ead97fe6c204f938b0eb
However that board has no flag info in the json yet so the flags won't be shown until it's updated (if it's ever updated).
You will also need to update the board list manually to get the flag info (Sites -> 4chan -> boards -> refresh button) otherwise it won't work.

**Comment by ghost** [comment]
Turns out it's just an April Fool's joke for this year
