### ISSUE TITLE
Not getting any notifications

### ISSUE THREAD

**Issue by GodTaisaku** [K1rakishou/Kuroba-Experimental#800]
My notifications still doesn't work til this day. The only time i get notifications is when i download an image. :(

**Comment by K1rakishou** [comment]
Do you have them enabled? In the app settings. Also, notifications don't show up for replies in threads you are currently viewing.

**Comment by GodTaisaku** [comment]
> Do you have them enabled? In the app settings. Also, notifications don't show up for replies in threads you are currently viewing.

Yes, i  definitely have them enabled. I always have KurobaEX on background but notifications still doesn't show.

**Comment by K1rakishou** [comment]
Then I need the logs but you will have to take the full logs via adb.
- Delete all bookmarks (you can make a backup before that and then restore from it).
- Set the foreground watcher to 30 seconds.
- Open any thread.
- Bookmark the thread.
- Mark any post as yours.
- Exit the thread (open any other thread). This is important because it won't show notifications for threads you are currently viewing. (Unless the app is in background/dead).
- Start taking the logs. (see https://github.com/K1rakishou/Kuroba-Experimental/wiki/Getting-application-logs-or-crashlogs-on-beta-or-release-builds)
- Reply to that post via the browser.
- Wait like 1 minute. Do not let the phone to go into sleep mode (keep the display on otherwise the background watcher will kick in and it has different timeouts). Do not close the app.
- End taking the logs.

**Comment by GodTaisaku** [comment]
> Then I need the logs but you will have to take the full logs via adb.
> - Delete all bookmarks (you can make a backup before that and then restore from it).
> - Set the foreground watcher to 30 seconds.
> - Open any thread.
> - Bookmark the thread.
> - Mark any post as yours.
> - Exit the thread (open any other thread). This is important because it won't show notifications for threads you are currently viewing. (Unless the app is in background/dead).
> - Start taking the logs. (see https://github.com/K1rakishou/Kuroba-Experimental/wiki/Getting-application-logs-or-crashlogs-on-beta-or-release-builds)
> - Reply to that post via the browser.
> - Wait like 1 minute. Do not let the phone to go into sleep mode (keep the display on otherwise the background watcher will kick in and it has different timeouts). Do not close the app.
> - End taking the logs.

I don't feel like turning on my laptop so i do it tomorrow. But for some reason the notifications worked after i clear all my bookmarks and setted the foreground watcher to 30 seconds. But then it didn't work again after importing my bookmarks.

**Comment by seniorm0ment** [comment]
I do not get notifications on lockscreen. Only failed download notifications show.
I get notifications for replies when the phone is unlocked. Only app I have this issue with.

Not sure if it's because disable sensitive notification info in lockscreen is disabled, but it should still show a notification coming through from KurobaEx.

GrapheneOS, Pixel 6 Pro

**Comment by K1rakishou** [comment]
@seniorm0ment 
I need to see the logs. See https://github.com/K1rakishou/Kuroba-Experimental/issues/800#issuecomment-1229206111
