### ISSUE TITLE
Auto load the rest of a Composite catalog

### ISSUE THREAD

**Issue by Liquid-Aristocracy** [K1rakishou/Kuroba-Experimental#818]
Without "load the rest", A composite catalog will only load the content in the first board (only after reading all in the first board would the rest being load).

It's not very convenient to manually choose the "load the rest" after every refresh. Is there a way to configure it in order to load automatically?

**Comment by K1rakishou** [comment]
No, there is no such option. The idea was to load them lazily while you scroll down. Once you reach the bottom of one catalog the next one will start getting loaded. It was implemented like that because loading 10 catalogs (in the worst case) it going to take a while so not everyone is going to wait for that to finish and instead will start complaining that it's slow, fix it, etc.

**Comment by Liquid-Aristocracy** [comment]
If posts of only one catalog is presented each time, then what's the point of making a composite? I might reach the end of a board and switch to another one to have an almost identical experience.

If the problem is response speed, then would loading in the background be a feasible option? For example load one catalog then load the rest in the background. When a new one loaded, reorder the post list.

**Comment by K1rakishou** [comment]
>If posts of only one catalog is presented each time, then what's the point of making a composite?

Posts of the next catalog are loaded once you reach the bottom of the current one. That's the main idea of composite catalogs. Of course this doesn't work great with stuff like catalog thread sorting since all catalogs need to be loaded to sort them correctly.

**Comment by Liquid-Aristocracy** [comment]
What do you think about the background loading thing I mentioned?

**Comment by K1rakishou** [comment]
I mean with auto-loading you still have to wait until everything is loaded if you want to start reading from the beginning, otherwise once everything is loaded and sorted threads that you are interested in might be moved at the beginning of the catalog so you will have to scroll back up. Leaving it like this seems like bad UX to me. You might be fine with it but most of other people will just think that it's broken.
I could block the UI with the "Loading" dialog sure, but then there would be almost no difference with the current implementation. Only two clicks less to make.

**Comment by Liquid-Aristocracy** [comment]
Well, ok then.
