### ISSUE TITLE
Error: You were warned. You must first view this warning to post again

### ISSUE THREAD

**Issue by deltabravozulu** [K1rakishou/Kuroba-Experimental#844]
Basically this: https://github.com/chandevel/Clover/issues/448

There is no apparent way to handle this in-app.

**Comment by K1rakishou** [comment]
This is a huge pain in the ass to test because you need to get warned.

**Comment by remedynotavailable** [comment]
I recently got this and fixed by opening https://www.4channel.org/banned
Maybe you can detect this link to handle it. The link basically the same as IP ban.
Also maybe the variant for https://www.4chan.org/banned

Or better parse any link in the message.
I remember the message in kurobaex literally the same as in the browser. I forgot to take the screenshot.
Since you able to parse the message. the link should be there too , right.

![Screenshot_20230405-092359_Kiwi Browser~01](https://user-images.githubusercontent.com/129032611/229958192-1810aea6-6215-4427-8945-eacca43997e4.png)

Try posting oot on  /lit/ maybe get warned.

**Comment by K1rakishou** [comment]
Should be (hopefully) fixed by https://github.com/K1rakishou/Kuroba-Experimental/commit/d61c96d883a5af8f1649c46807f25f723ece9304
