### ISSUE TITLE
App keeps crashing while typing comments on 4Chan

### ISSUE THREAD

**Issue by zilla249** [K1rakishou/Kuroba-Experimental#853]
When typing comments on 4chan, app will lag to a halt, and then crash. 
![Screenshot_20230103_232857](https://user-images.githubusercontent.com/114614208/210485917-c28e6a0a-d9df-4271-83a0-d4157314b3ce.jpg)

**Comment by K1rakishou** [comment]
Oh yeah, I got like 50 crash reports from you (or more like from people using similar samsung phones) but unfortunately this seems like a Samsung bug. Because all of these crashes come from samsung phones and they all occur in some external applicatation (which is most likely the keyboard or something related to it) so I most likely won't be able to fix it, unfortunately. I even tried to suppress them, but alas, it didn't help.

https://github.com/KurobaExReports/Reports/issues?q=is%3Aissue+TransactionTooLargeException+in%3Atitle
https://github.com/KurobaExReports/Reports/issues?q=is%3Aissue+DeadSystemException+in%3Atitle

**Comment by zilla249** [comment]
Dang. Okay, thanks a lot for the quick response my man.

**Comment by K1rakishou** [comment]
@zilla249 
Some anon in a thread says that disabling keyboard auto-correct setting helped him with crashes.

**Comment by zilla249** [comment]
Nice, I'll give it a try and write back if it fixes the issue. Thanks
