### ISSUE TITLE
Full media files don't load after updating to v1.3.26

### ISSUE THREAD

**Issue by obscenelyvague** [K1rakishou/Kuroba-Experimental#920]
Previews are fine but when tapped to view in full size, no images, webms or gifs load - the rotating progress bar circle doesn't even show up.

Logs taken right after attempting to view 1691752655992116.gif and 1691746716218102.png from two different threads. Problem is present across all chans. 

Exceeds GitHub issue tracker character limit: https://katb.in/unugovulase

**Comment by obscenelyvague** [comment]
On a fresh install of 1.3.26 it does work but there's a second tap that's required to get the file to start downloading in full size. First tap opens up the thumbnail/preview into the viewer. I downgraded to 1.3.25 for now.

**Comment by K1rakishou** [comment]
There were some changes to how media is loaded when opened. In the previous versions if you were connected to a WiFi and in the application settings it was set to load full media automatically when connected to WiFi then it would be automatically loaded. Now instead of just checking if we are connected to WiFi it checks if the current network is metered or not (some WiFi networks can still be metered). So this means that you are currently connected to a metered network. In this case you can load media manually by tapping it once. 
You can go to application settings (Media) and change Media Loading settings.

![image](https://github.com/K1rakishou/Kuroba-Experimental/assets/10332458/ee9a491e-19f5-4466-a20f-781cac402083)

**Comment by obscenelyvague** [comment]
Yes I'm on a metered network (hotspot). Changed those two settings and everything's back to normal. Thanks.
