### ISSUE TITLE
Captcha fails silently

### ISSUE THREAD

**Issue by CreatureDev** [K1rakishou/Kuroba-Experimental#990]
When the captcha fails on a post it does not produce an error message and proceeds as if the post succeeded
This is what causes #988

**Comment by K1rakishou** [comment]
Yeah, and that happens on the server which means I can't really do much here. Probably some new anti-spam feature of 4chan.

**Comment by K1rakishou** [comment]
Ok, I think I know how to make it at the very least not to consume everything you have typed if this happens again. I could make a GET request to the thread and search for a post that the server returns in the HTML. And if it doesn't exist there then I could show an error instead of assuming it went through.

**Comment by K1rakishou** [comment]
A new mechanism was implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/2ee0c2ca050b4bb8bce98f759fa424b3363a825f that will check whether a website actually has your post after you send it and the server returns a response. If the thread doesn't have the post, your local message won't be discarded so you can try again.
